config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('core.urls')),
                  path('task/', include('task.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),
         name='login')
]

task/urls.py
from django.urls import path
from . import views

app_name = 'task'
urlpatterns = [
    path('', views.tasks, name='tasks'),
    path('<int:pk>/list_table/', views.list_table, name='list_table'),
    path('lists/', views.lists, name='lists'),
    path('new_task/', views.new_task, name='new_task'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit_task, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

core/models.py
from django.db import models

# Create your models here.

task/models.py
from django.db import models
from django.contrib.auth.models import User


class List(models.Model):
    name = models.CharField(max_length=250)
    color = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = 'Lists'

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=250)
    body = models.TextField()
    list = models.ForeignKey(List, related_name='tasks', on_delete=models.CASCADE)
    start_time = models.DateField()
    end_time = models.DateField()
    is_complete = models.BooleanField(default=False)
    author = models.ForeignKey(User, related_name='author', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ism',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Parol',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ism',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Parol',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Parolni tasdiqlang',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

task/forms.py
from django import forms
from .models import Task

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border mt-1'


class NewTask(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'list', 'body', 'start_time', 'end_time')
        widgets = {
            'list': forms.Select(attrs={'class': INPUT_CLASSES}),
            'name': forms.TextInput(attrs={'class': INPUT_CLASSES}),
            'body': forms.Textarea(attrs={'class': INPUT_CLASSES}),
            'start_time': forms.DateTimeInput(attrs={'class': INPUT_CLASSES}),
            'end_time': forms.DateTimeInput(attrs={'class': INPUT_CLASSES}),
        }


class EditTask(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'list', 'body', 'start_time', 'end_time')
        widgets = {
            'list': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'body': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'start_time': forms.DateTimeInput(attrs={'class': INPUT_CLASSES}),
            'end_time': forms.DateTimeInput(attrs={'class': INPUT_CLASSES}),
        }

core/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm


def index(request):
    return render(request, 'core/index.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {
        'form': form
    })


def logout(request):
    return render(request, 'core/main.html')

task/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import NewTask, EditTask
from .models import Task, List


@login_required
def lists(request):
    lists = List.objects.all()
    tasks = Task.objects.all()
    return render(request, 'task/lists.html', {
        'lists': lists,
        'tasks': tasks,
    })


@login_required
def list_table(request, pk):
    list = get_object_or_404(List, pk=pk)
    tasks = Task.objects.filter(list=list)
    return render(request, 'task/list_table.html', {
        'list': list,
        'tasks': tasks
    })


@login_required
def tasks(request):
    tasks = Task.objects.filter(is_complete=False)
    list_id = request.GET.get('list', 0)
    count = Task.objects.all().count()
    return render(request, 'task/tasks.html', {
        'tasks': tasks,
        'list_id': int(list_id),
        'count': count
    })


@login_required
def detail(request, pk):
    task = get_object_or_404(Task, pk=pk)
    is_author = request.user == task.author
    list_id = request.GET.get('list', 0)
    lists = List.objects.all()
    return render(request, 'task/detail.html', {
        'task': task,
        'is_author': is_author,
        'list_id': int(list_id),
        'lists': lists
    })


@login_required
def new_task(request):
    if request.method == 'POST':
        form = NewTask(request.POST, request.FILES)
        if form.is_valid():
            task = form.save(commit=False)
            task.author = request.user
            task.save()
            return redirect('task:detail', pk=task.id)
    else:
        form = NewTask()
        return render(request, 'task/new_task.html', {
            'form': form,
            'title': 'Add new task'
        })


@login_required
def delete(request, pk):
    task = get_object_or_404(Task, pk=pk, author=request.user)
    task.delete()
    return redirect('task:tasks')


@login_required
def edit_task(request, pk):
    task = get_object_or_404(Task, pk=pk, author=request.user)
    if request.method == 'POST':
        form = EditTask(request.POST, request.FILES, instance=task)
        if form.is_valid():
            form.save()
            return redirect('task:detail', pk=task.id)
    else:
        form = EditTask(instance=task)
    return render(request, 'task/new_task.html', {
        'form': form,
        'title': 'Edit task'
    })

core/templates/core/base.html
{%load static%}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title%}{% endblock%}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
    <!--Fontawesomni ulash-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
          integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <!--Fontawesomni ulash-->
</head>
<body>
<!-- component -->
<div class="w-full h-full">
    <dh-component>
        <div class="flex flex-no-wrap">
            <!-- Sidebar starts -->
            <div style="min-height: 716px"
                 class="w-64 absolute sm:relative bg-gray-800 shadow md:h-full flex-col justify-between hidden sm:flex">
                <div class="px-8">
                    <div class="h-16 w-full flex items-center">
                        <a class="flex items-center mt-5">
                            <img src="{% static 'images/out.png' %}" class="h-16 mr-3" alt="My Logo"/>
                            <span class="self-center text-2xl font-semibold whitespace-nowrap text-white">{{user.username}}</span>
                        </a>
                    </div>
                    <h1 class="text-gray-300 text-xl mt-8" style="font-weight:bold">Menu</h1>
                    <li class="flex w-full justify-between text-gray-300 cursor-pointer items-center mb-6 ms-4 mt-4">
                        <a href="{%url 'core:index' %}"
                           class="flex items-center focus:outline-none focus:ring-2 focus:ring-white">
                            <span class="text-sm"><i class="fa-solid fa-house me-2"></i>Main</span>
                        </a>
                    </li>
                    <ul class="mt-4">
                        <!--Tasks-->
                        <h1 class="text-gray-300 text-sm mb-2 ms-2" style="font-weight:bold">TASKS</h1>
                        <li class="ms-4 flex w-full justify-between text-gray-400 hover:text-gray-300 cursor-pointer items-center mb-6">
                            <a href="{% url 'task:tasks'%}"
                               class="flex items-center focus:outline-none focus:ring-2 focus:ring-white">
                                <i class="fa-solid fa-diamond me-2" style="color:white;"></i>
                                <span class="text-sm">All tasks</span>
                            </a>
                        </li>
                        <li class="flex w-full justify-between text-gray-400 hover:text-gray-300 cursor-pointer items-center mb-6 ms-4">
                            <a href="{% url 'task:new_task' %}"
                               class="flex items-center focus:outline-none focus:ring-2 focus:ring-white">
                                <span class="text-sm"><i class="fa-solid fa-plus me-2"></i>New task</span>
                            </a>
                        </li>

                        <!--Lists-->
                        <div class="ms-2 text-gray-300 text-sm mb-2" style="font-weight:bold">LISTS</div>
                        <li class="ms-4 flex w-full justify-between text-gray-400 hover:text-gray-300 cursor-pointer items-center mb-6">
                            <a href="{% url 'task:lists' %}"
                               class="flex items-center focus:outline-none focus:ring-2 focus:ring-white">
                                <i class="fa-solid fa-diamond me-2" style="color:red;"></i>
                                <span class="text-sm">Lists table</span>
                            </a>
                        </li>
                        <div class="ms-2 text-gray-300 text-sm mb-2" style="font-weight:bold">SETTINGS</div>
                        <li class="ms-4 flex w-full justify-between text-gray-400 hover:text-gray-300 cursor-pointer items-center mb-6">
                            <a href="{% url 'core:logout'%}"
                               class="flex items-center focus:outline-none focus:ring-2 focus:ring-white">
                                <i class="fa-solid fa-right-from-bracket me-2"></i>
                                <span class="text-sm">Logout</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Sidebar ends -->
            <!-- Remove class [ h-64 ] when adding a card block -->
            <div class="container mx-auto py-10 h-64 md:w-4/5 w-11/12 px-6">
                <!-- Remove class [ border-dashed border-2 border-gray-300 ] to remove dotted border -->
                <div class="w-full h-full">
                    {%block content%}

                    {%endblock%}
                </div>
            </div>
        </div>
    </dh-component>
</div>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Xush kelibsiz{% endblock %}
{% block content %}
<h1 class="text-center mt-48 rounded-xl" style="font-size:100px;color:white;font-weight:600;background-color:blue;">WELCOME!!!</h1>
{% endblock content %}

core/templates/core/main.html
{%load static%}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
    <!--Fontawesomni ulash-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
          integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <!--Fontawesomni ulash-->
    <title>Xush kelibsiz!</title>
</head>
<body>
<div>

<section class="bg-center bg-no-repeat bg-[url('https://wallpapercave.co    m/wp/wp9352908.jpg')] bg-gray-700 bg-blend-multiply">
    <div class="px-4 mx-auto max-w-screen-xl text-center py-24 lg:py-56">
        <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-white md:text-5xl lg:text-6xl">Bizning web sayt sizning xizmatingizda!</h1>
        <p class="mb-8 text-lg font-normal text-gray-300 lg:text-xl sm:px-16 lg:px-48">Bizning web sayt bilan kunlik, haftalik rejalaringizni tuzing!</p>
        <div class="flex flex-col space-y-4 sm:flex-row sm:justify-center sm:space-y-0 sm:space-x-4">
            <a href="{% url 'core:login' %}" class="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-white rounded-lg bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900">
                Kirish
                <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
            </a>
            <a href="{% url 'core:signup' %}" class="inline-flex justify-center hover:text-gray-900 items-center py-3 px-5 text-base font-medium text-center text-white rounded-lg border border-white hover:bg-gray-100 focus:ring-4 focus:ring-gray-400">
                Ro'yxatdan o'tish
            </a>
        </div>
    </div>
</section>

    {% block content%}
    {% endblock %}

</div>
<footer class="bg-white dark:bg-gray-900">
    <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
        <div class="md:flex md:justify-between">
            <div class="mb-6 md:mb-0">
                <a class="flex items-center">
                    <img src="{% static 'images/out.png' %}" class="h-8 mr-3" alt="My Logo"/>
                    <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">KRDev</span>
                </a>
            </div>
            <div class="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-3">
                <div>
                    <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Ijtimoiy tarmoqlar</h2>
                    <ul class="text-gray-600 dark:text-gray-400 font-medium">
                        <li class="mb-4">
                            <a href="https://github.com/KRDevs" class="hover:underline ">Github</a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/k_raximov_03/" class="hover:underline">Instagram</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8"/>
        <div class="sm:flex sm:items-center sm:justify-between">
          <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 KRDev</a>
          </span>
            <div class="flex mt-4 space-x-6 sm:justify-center sm:mt-0">
                <a href="https://www.facebook.com/profile.php?id=100065750137125" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                        <path fill-rule="evenodd"
                              d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
                              clip-rule="evenodd"/>
                    </svg>
                    <span class="sr-only">Facebook page</span>
                </a>
                <a href="https://www.instagram.com/k_raximov_03/" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                        <path fill-rule="evenodd"
                              d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z"
                              clip-rule="evenodd"/>
                    </svg>
                    <span class="sr-only">Instagram page</span>
                </a>
                <a href="https://github.com/KRDevs" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                        <path fill-rule="evenodd"
                              d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                              clip-rule="evenodd"/>
                    </svg>
                    <span class="sr-only">GitHub account</span>
                </a>
            </div>
        </div>
    </div>
</footer>

</body>
</html>

task/templates/task/detail.html
{% extends 'core/base.html' %}
{% block title %}{{ task.name }}{% endblock %}
{% block content %}
<div class="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
    <div><i class="fa-solid fa-signature me-2 mt-2"></i>{{task.name}}</div>
    <div><i class="fa-solid fa-file-signature me-2 mt-2"></i>{{task.body}}</div>
    <div><i class="fa-solid fa-diamond me-2 mt-2" style="color:{{task.list.color}};"></i>{{task.list.name}}</div>
    <div><i class="fa-regular fa-calendar-days me-2 mt-2"></i>{{task.start_time}}-{{task.end_time}}</div>
    <div><i class="fa-solid fa-user me-2 mt-2"></i>{{task.author}}</div>
    <div class="mt-4">
        <a href="{% url 'task:edit' task.id %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 inline-flex items-center border border-blue-700 rounded">
            <span> <i class="fa-solid fa-pen-to-square me-1"></i> Edit</span>
        </a>
        <a href="{% url 'task:delete' task.id %}" class="ms-2 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 inline-flex items-center border border-blue-700 rounded">
            <span><i class="fa-solid fa-trash-can me-1"></i>Delete</span>
        </a>
    </div>
</div>
{% endblock %}

task/templates/task/tasks.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<!-- component -->
<div class="max-w-lg mx-auto my-10 bg-white p-8 rounded-xl shadow shadow-slate-300">
    <div class="flex flex-row justify-between items-center">
        <div>
            <h1 class="text-3xl font-medium">Tasks list</h1>
        </div>
    </div>
    <p class="text-slate-500">Hello, here are your tasks</p>

    <div id="tasks" class="my-5">
        {% for task in tasks %}
        <div id="task"
             class="flex justify-between items-center border-b border-slate-200 py-3 px-2 border-l-4  border-l-transparent bg-gradient-to-r from-transparent to-transparent hover:from-slate-100 transition ease-linear duration-150">
            <div class="inline-flex items-center space-x-2">
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                         stroke="currentColor"
                         class="w-6 h-6 text-slate-500 hover:text-indigo-600 hover:cursor-pointer">
                        <path stroke-linecap="round" stroke-linejoin="round"
                              d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
                    </svg>
                </div>
                <a href="{% url 'task:detail' task.id %}">{{task.name}}</a>
            </div>
            <div>
                <a href="{% url 'task:edit' task.id %}"><i class="fa-regular fa-pen-to-square" style="color:blue;"></i></a>
                <a href="{% url 'task:delete' task.id %}"><i class="fa-regular fa-trash-can" style="color:red;"></i></a>
            </div>
        </div>
        {%endfor%}
        <p class="text-center mt-4">{{tasks.count}} tasks are here</p>
    </div>
</div>
{%endblock%}

task/templates/task/today.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<!-- component -->
<div class="max-w-lg mx-auto my-10 bg-white p-8 rounded-xl shadow shadow-slate-300">
    <div class="flex flex-row justify-between items-center">
        <div>
            <h1 class="text-3xl font-medium">Tasks list</h1>
        </div>
    </div>
    <p class="text-slate-500">Hello, here are your tasks</p>

    <div id="tasks" class="my-5">
            {% for task in tasks %}
            <div id="task"
                 class="flex justify-between items-center border-b border-slate-200 py-3 px-2 border-l-4  border-l-transparent bg-gradient-to-r from-transparent to-transparent hover:from-slate-100 transition ease-linear duration-150">
                <div class="inline-flex items-center space-x-2">
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                             stroke="currentColor"
                             class="w-6 h-6 text-slate-500 hover:text-indigo-600 hover:cursor-pointer">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                  d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
                        </svg>
                    </div>
                    <a href="{% url 'task:detail' task.id %}">{{task.name}}</a>
                </div>
                <div>
                    <a href="{% url 'task:edit' task.id %}"><i class="fa-regular fa-pen-to-square" style="color:blue;"></i></a>
                    <a href="{% url 'task:delete' task.id %}"><i class="fa-regular fa-trash-can" style="color:red;"></i></a>
                </div>
            </div>
            {%endfor%}
    </div>
</div>
{%endblock%}